@echo off
echo Check status...
git status

echo Adding config files force...
git add package.json vercel.json

echo Committing...
git commit -m "Add package.json and vercel.json for deployment"

echo Pushing...
git push origin main
